### ISSUE TITLE
Füllstandssensor

### ISSUE THREAD

**Issue by achmet9948** [DIY-Blub/plant-watering-system1.0#4]
Hallo und moin, 

ich habe dein Projekt nachgebaut und muss sagen, es klappt gut (zumindest mit Rasbian Jessi) - Mit Buster hat der MCP nur den Wert 0 zurückgegben. Aber das ist ein anderes Thema.

Meine Frage: Ist es möglich, den Feuchtigkeitssensor als Füllstand zu nutzen? Hatte gedacht ich nehme dann den Digitalen Wert und lasse zwei Drähte ins Wasserresorvior hängen. Wenn dann die Drähte trocken liegen, soll das Script stoppen. 
Wie kann man das am besten in dein Skript implementieren?

**Comment by DIY-Blub** [comment]
Hallo, 
es freut mich sehr das zu hören :)

**bezüglich Problem mit Buster:**
Bei Buster muss man, warum auch immer, die maximale Lesegeschwindigkeit mit spi.max_speed_hz=1000000 begrenzen, also z.B.: (ungetestet!)
```
    def open(self):
        self.spi.open(self.bus, self.device)
        self.spi.max_speed_hz=1000000
```

**zu deiner Frage:**
Ich rate zum Einsatz eines [Wasserstandssensor](https://www.amazon.de/ARCELI-Wasserstandssensor-Flüssigkeit-Wassertropfen-Erkennung/dp/B07BP7B9TR/)
Da bekommst du einen korrekten Wert vom Wasser-Füllstand. Die Abfrage sollte nach dem Pumpendurchlauf ausgeführt werden, also am Ende der Datei folgendes anführen (ungetestet!):
```
# Wasserstand ABFRAGEN
waterchannel = 6   # MCP3008-Channel vom Wassersensor
GPIO.output(strom_sensoren, GPIO.HIGH)
time.sleep(1)
spi = SpiDev()
spi.open(0,0)
# spi.max_speed_hz=1000000    # nur bei Version Buster erforderlich
adc1 = spi.xfer2([1, (8 + waterchannel) << 4, 0])
wasserstand = ((adc1[1] & 3) << 8) + adc1[2]
spi.close()
time.sleep(1)
GPIO.output(strom_sensoren, GPIO.LOW)

print("Wasserstand, Wert: " + str(wasserstand))
```
Die Variable "wasserstand" kann man noch in Prozent umrechnen oder man macht ein Ampelsystem (wert über x --> grün; wert zwischen x und y --> gelb; wert unter y --> rot)

**Comment by achmet9948** [comment]
Danke für deine schnelle Reaktion. 
Mir reicht es lediglich, dass das Skript stoppt, wenn nicht mehr genügend Wasser da ist, damit das Skript abbricht, damit die Pumpe nicht kaputt geht, wenn diese trocken läuft.

**Comment by DIY-Blub** [comment]
Man kann die watering-funktion (Zeile 32) ausbauen um vor dem aktivieren der Pumpe den Wasserstand zu prüfen.
```
def watering(relay,pump):
    # WASSERSTAND - Script
    if wasserstand:
        GPIO.output(relay, False)
        time.sleep(pump)
        GPIO.output(relay, True)
        time.sleep(1)
```
die Variable "wasserstand" ist ab einem zu niedrigem Wert auf "False" zu setzen.

**Comment by achmet9948** [comment]
Ich kenne mich mit Python/Programmieren leider so gar nicht aus.... 
Wie muss ich das schreiben, wenn ich den Sensor direkt an die RPI anschließe, und sage, dass wenn der Digital Ausgang = 1 ist, das Script weitermachen kann und wenn der Digital Ausgang = 0 ist, das Script abbricht.

**Comment by DIY-Blub** [comment]
Du brauchst 2 Pins am RasPi. Den einen als Ausgang (Signal), den anderen als Eingang (Status).
Hab da mal schnell was zusammen kopiert (ungetestet!) .... **Verwendung auf eigene Gefahr!**

```
# PINS FESTLEGEN - ergänze
wasserstand_Signal = 16
wasserstand_Status = 18

# GPIO SETUP - ergänze
GPIO.setup(wasserstand_Signal, GPIO.OUT)
GPIO.setup(wasserstand_Status, GPIO.IN, pull_up_down=GPIO.PUD_UP)

# Funktion "watering" ändern zu
def watering(relay,pump):
    GPIO.output(wasserstand_Signal, GPIO.HIGH)
    time.sleep(1)
    GPIO.add_event_detect(wasserstand_Status,GPIO.RISING)
    if GPIO.event_detected(wasserstand_Status):
        GPIO.output(relay, False)
        time.sleep(pump)
        GPIO.output(relay, True)
        time.sleep(1)
    GPIO.output(wasserstand_Signal, GPIO.LOW)
```

Wirf auch mal einen Blick in die [Lektüre für Neueinsteiger](https://www.cenz.at/lekt%C3%BCre) - dort gibt es einen Link zu Video-Tutorials für Python.

**Comment by achmet9948** [comment]
Danke für deine Mühe. 
Was meinst du mit den zwei Pins am Rasp. Der Sensor hat ja einen Digitalen Output als Pin. Wo muss der zweite Angeschlossen werden?

**Comment by achmet9948** [comment]
Danke für deine Mühe. 
Was meinst du mit den zwei Pins am Rasp. Der Sensor hat ja einen Digitalen Output als Pin. Daher sollte ja auch ein Digitaler Wert an der RPI ankommen oder und ein zweiter Pin sollte nicht nötig sein oder stelle ich mir das zu einfach vor. 
Ich denke mir folgendes:
Wenn das Wasser die Brücke zwischen den Sensor des Feuchtigkeitssensor schafft, schaltet der Sensor die LED für den DO an.

**Comment by DIY-Blub** [comment]
Aso ja, da hast du recht. Ich gab nicht daran gedacht, dass auf der Platine ein Potentiometer vorhanden ist. Sorry, war mit dem Kopf bei einem anderen Bodenfeuchtigkeitssensor.
hier der adaptierte code (ungetestet!):
```
# PINS FESTLEGEN - ergänze
wasserstand_Status = 18

# GPIO SETUP - ergänze
GPIO.setup(wasserstand_Status, GPIO.IN, pull_up_down=GPIO.PUD_UP)

# Funktion "watering" ändern zu
def watering(relay,pump):
    GPIO.add_event_detect(wasserstand_Status,GPIO.RISING)
    if GPIO.event_detected(wasserstand_Status):
        GPIO.output(relay, False)
        time.sleep(pump)
        GPIO.output(relay, True)
        time.sleep(1)
```
